### ISSUE TITLE
py3 compatibility usse for home grown WaitableEvent

### ISSUE THREAD

**Issue by plajjan** [plajjan/bgworker#3]
Pretty sure this is due to py3isms. I wrote the code on py2.
```
ERROR> 03-Jul-2019::16:24:28.54 bgworker ComponentThread:main: - Traceback (most recent call last):
  File "/home/kll/ncs-4.7.4.2/src/ncs/pyapi/ncs_pyvm/ncsthreads.py", line 173, in run
    self.main._run()
  File "/home/kll/ncs-4.7.4.2/src/ncs/pyapi/ncs/application.py", line 218, in _run
    self.teardown()
  File "/home/kll/ncs-4.7.4.2/ncs-run/state/packages-in-use/1/bgworker/python/bgworker/main.py", line 35, in teardown
    self.p.stop()
  File "/home/kll/ncs-4.7.4.2/ncs-run/state/packages-in-use/1/bgworker/python/bgworker/background_process.py", line 126, in stop
    self.ha_event_listener.stop()
  File "/home/kll/ncs-4.7.4.2/ncs-run/state/packages-in-use/1/bgworker/python/bgworker/background_process.py", line 235, in stop
    self.exit_flag.set()
  File "/home/kll/ncs-4.7.4.2/ncs-run/state/packages-in-use/1/bgworker/python/bgworker/background_process.py", line 263, in set
    os.write(self._write_fd, '1')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by plajjan** [comment]
Fixed in 04bec41cad18636f99342a0deef156b0d779077a. Closing.
